#!/usr/bin/env bash
# Resolve SourceBans++ plugin version constants (mirrors web/Sbpp\Version::resolve).
#
# Tier 1: SBPP_RELEASE_VERSION (release CI — the semver tag, e.g. 2.0.0)
# Tier 2: web/configs/version.json (release tarball / local file from panel)
# Tier 3: git describe --tags --always (+ optional git rev-parse --short HEAD)
# Tier 4: literal "dev"
#
# Writes game/addons/sourcemod/scripting/include/sbpp_version.inc
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SCRIPTING_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../../../../.." && pwd)"
OUT="${SCRIPTING_DIR}/include/sbpp_version.inc"
VERSION_JSON="${SBPP_VERSION_JSON:-${REPO_ROOT}/web/configs/version.json}"

version=""
git_sha=""

if [[ -n "${SBPP_RELEASE_VERSION:-}" ]]; then
  version="${SBPP_RELEASE_VERSION}"
  git_sha="$(git -C "${REPO_ROOT}" rev-parse --short HEAD 2>/dev/null || true)"
elif [[ -r "${VERSION_JSON}" ]]; then
  version="$(php -r '
    $d = json_decode(file_get_contents($argv[1]), true);
    if (!is_array($d) || !isset($d["version"])) { exit(1); }
    echo (string) $d["version"];
  ' "${VERSION_JSON}" 2>/dev/null || true)"
  git_sha="$(php -r '
    $d = json_decode(file_get_contents($argv[1]), true);
    echo is_array($d) && isset($d["git"]) ? (string) $d["git"] : "";
  ' "${VERSION_JSON}" 2>/dev/null || true)"
fi

if [[ -z "${version}" ]]; then
  version="$(git -C "${REPO_ROOT}" describe --tags --always 2>/dev/null | tr -d '\n' || true)"
  git_sha="$(git -C "${REPO_ROOT}" rev-parse --short HEAD 2>/dev/null | tr -d '\n' || true)"
fi

if [[ -z "${version}" ]]; then
  version="dev"
  git_sha=""
fi

# Native API epoch (panel 2.x line). Bump MAJOR only on breaking native contract.
# Aligned with SBPP_RELEASE_VERSION on tag builds; fixed at 2 between releases.
api_major=2
api_minor=0
sb_major="dev"
sb_minor="0"
sb_patch="0"

if [[ -n "${SBPP_RELEASE_VERSION:-}" ]] && [[ "${SBPP_RELEASE_VERSION}" =~ ^([0-9]+)\.([0-9]+)\.([0-9]+) ]]; then
  api_major="${BASH_REMATCH[1]}"
  api_minor="${BASH_REMATCH[2]}"
  sb_major="${BASH_REMATCH[1]}"
  sb_minor="${BASH_REMATCH[2]}"
  sb_patch="${BASH_REMATCH[3]}"
elif [[ "${version}" =~ ^([0-9]+)\.([0-9]+)\.([0-9]+) ]]; then
  # git describe on a semver tag (exact or -N-gSHA) — SB_VERSION is the full string.
  sb_major="${BASH_REMATCH[1]}"
  sb_minor="${BASH_REMATCH[2]}"
  sb_patch="${BASH_REMATCH[3]}"
fi

escape_sp() {
  printf '%s' "$1" | sed "s/\\\\/\\\\\\\\/g; s/\"/\\\\\"/g"
}

version_escaped="$(escape_sp "${version}")"
git_comment=""
if [[ -n "${git_sha}" ]]; then
  git_comment=" (git ${git_sha})"
fi

cat > "${OUT}" <<EOF
// *************************************************************************
//  Auto-generated by scripts/resolve-plugin-version.sh — do not edit.
//  Resolved: ${version}${git_comment}
// *************************************************************************

#if defined _sbpp_version_included
#endinput
#endif
#define _sbpp_version_included

#define MAJOR_REVISION                    ${api_major}
#define MINOR_REVISION                    ${api_minor}

#define SOURCEBANSPP_VERSION_MAJOR        MAJOR_REVISION
#define SOURCEBANSPP_VERSION_MINOR        MINOR_REVISION

#define SB_VERSION_MAJOR                  "${sb_major}"
#define SB_VERSION_MINOR                  "${sb_minor}"
#define SB_VERSION_PATCH                    "${sb_patch}"

#define SB_VERSION                        "${version_escaped}"

EOF

echo "resolve-plugin-version: wrote ${OUT} (version=${version}, api_major=${api_major}, api_minor=${api_minor})"
