#!/usr/bin/env bash
# Resolve SourceBans++ plugin version constants.
#
# Panel (Sbpp\Version::resolve): version.json → git describe → "dev"
# Plugin adds tier 0 for release CI only: SBPP_RELEASE_VERSION (semver tag)
#
# Writes include/sbpp_version.inc (override path via SBPP_VERSION_INC_OUT).
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SCRIPTING_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../../../../.." && pwd)"
OUT="${SBPP_VERSION_INC_OUT:-${SCRIPTING_DIR}/include/sbpp_version.inc}"
VERSION_JSON="${SBPP_VERSION_JSON:-${REPO_ROOT}/web/configs/version.json}"

version=""
git_sha=""

if [[ -n "${SBPP_RELEASE_VERSION:-}" ]]; then
  version="${SBPP_RELEASE_VERSION}"
  git_sha="$(git -C "${REPO_ROOT}" rev-parse --short HEAD 2>/dev/null || true)"
elif [[ -r "${VERSION_JSON}" ]]; then
  if ! command -v php >/dev/null 2>&1; then
    echo "resolve-plugin-version: php is required to read ${VERSION_JSON}" >&2
    exit 1
  fi
  version="$(php -r '
    $d = json_decode(file_get_contents($argv[1]), true);
    if (!is_array($d) || !isset($d["version"])) { exit(1); }
    echo (string) $d["version"];
  ' "${VERSION_JSON}")"
  git_sha="$(php -r '
    $d = json_decode(file_get_contents($argv[1]), true);
    echo is_array($d) && isset($d["git"]) ? (string) $d["git"] : "";
  ' "${VERSION_JSON}")"
fi

if [[ -z "${version}" ]]; then
  version="$(git -C "${REPO_ROOT}" describe --tags --always 2>/dev/null | tr -d '\n' || true)"
  git_sha="$(git -C "${REPO_ROOT}" rev-parse --short HEAD 2>/dev/null | tr -d '\n' || true)"
fi

if [[ -z "${version}" ]]; then
  version="dev"
  git_sha=""
fi

# Native API epoch — NOT panel semver minor. Bump MINOR_REVISION manually when
# shipping additive natives; bump MAJOR only on breaking native contract.
api_major=2
api_minor=0

sb_major="dev"
sb_minor="0"
sb_patch="0"

if [[ -n "${SBPP_RELEASE_VERSION:-}" ]] && [[ "${SBPP_RELEASE_VERSION}" =~ ^([0-9]+)\.([0-9]+)\.([0-9]+) ]]; then
  # Panel semver triplet only — MAJOR_REVISION stays the fixed native API epoch above.
  sb_major="${BASH_REMATCH[1]}"
  sb_minor="${BASH_REMATCH[2]}"
  sb_patch="${BASH_REMATCH[3]}"
elif [[ "${version}" =~ ^([0-9]+)\.([0-9]+)\.([0-9]+)$ ]]; then
  # Exact semver only (not describe/rc suffixes) — triplet macros match SB_VERSION.
  sb_major="${BASH_REMATCH[1]}"
  sb_minor="${BASH_REMATCH[2]}"
  sb_patch="${BASH_REMATCH[3]}"
fi

escape_sp() {
  printf '%s' "$1" | tr -d '\r\n\t' | sed 's/\\/\\\\/g; s/"/\\"/g'
}

sanitize_comment() {
  # Allow alnum plus . _ - + (no tr ranges — locale-safe).
  printf '%s' "$1" | tr -cd '[:alnum:]._+-' | head -c 120
}

version_escaped="$(escape_sp "${version}")"
version_comment="$(sanitize_comment "${version}")"
git_comment=""
if [[ -n "${git_sha}" ]]; then
  git_comment=" (git $(sanitize_comment "${git_sha}"))"
fi

cat > "${OUT}" <<EOF
// *************************************************************************
//  Auto-generated by scripts/resolve-plugin-version.sh — do not edit.
//  Resolved: ${version_comment}${git_comment}
// *************************************************************************

#if defined _sbpp_version_included
#endinput
#endif
#define _sbpp_version_included

#define MAJOR_REVISION                    ${api_major}
#define MINOR_REVISION                    ${api_minor}

#define SOURCEBANSPP_VERSION_MAJOR        MAJOR_REVISION
#define SOURCEBANSPP_VERSION_MINOR        MINOR_REVISION

#define SB_VERSION_MAJOR                  "${sb_major}"
#define SB_VERSION_MINOR                  "${sb_minor}"
#define SB_VERSION_PATCH                  "${sb_patch}"

#define SB_VERSION                        "${version_escaped}"

EOF

echo "resolve-plugin-version: wrote ${OUT} (version=${version}, api_major=${api_major}, api_minor=${api_minor})"
