#!/usr/bin/env bash
# Web container entrypoint. Idempotent — safe to run on every container start.
#   1. Wait for the database to accept connections.
#   2. Render web/config.php from environment variables if it's missing/empty.
#   3. Run `composer install` if vendor/ is absent.
#   4. Make sure cache/ is writable.
#   5. exec the original CMD (apache2-foreground).

set -euo pipefail

WEB_ROOT="/var/www/html/web"
CONFIG_FILE="${WEB_ROOT}/config.php"

: "${DB_HOST:=db}"
: "${DB_PORT:=3306}"
: "${DB_NAME:=sourcebans}"
: "${DB_USER:=sourcebans}"
: "${DB_PASS:=sourcebans}"
: "${DB_PREFIX:=sb}"
: "${DB_CHARSET:=utf8mb4}"
: "${STEAMAPIKEY:=}"
: "${SB_EMAIL:=admin@example.test}"
: "${SB_NEW_SALT:=\$5\$}"
: "${SB_SECRET_KEY:=}"

log() { printf '[entrypoint] %s\n' "$*"; }

wait_for_db() {
    log "waiting for ${DB_HOST}:${DB_PORT} ..."
    local tries=60
    until mysqladmin ping -h"${DB_HOST}" -P"${DB_PORT}" -u"${DB_USER}" -p"${DB_PASS}" --skip-ssl --silent 2>/dev/null; do
        tries=$((tries - 1))
        if [[ $tries -le 0 ]]; then
            log "database never came up — giving up"
            exit 1
        fi
        sleep 1
    done
    log "database is up"
}

render_config() {
    if [[ -s "${CONFIG_FILE}" ]]; then
        log "config.php already present, leaving it alone"
        return
    fi
    log "rendering config.php from environment"
    if [[ -z "${SB_SECRET_KEY}" ]]; then
        SB_SECRET_KEY="$(openssl rand -base64 47 | tr -d '\n')"
    fi
    cat >"${CONFIG_FILE}" <<PHP
<?php
// Generated by docker/web-entrypoint on $(date -u +%FT%TZ). Edit env vars in
// .env (or docker-compose.override.yml) and recreate the web container if
// you want different values, or just edit this file directly — it won't be
// regenerated while it has content.
if (!defined('IN_SB')) {
    echo 'You should not be here. Only follow links!';
    die();
}
define('DB_HOST', '${DB_HOST}');
define('DB_USER', '${DB_USER}');
define('DB_PASS', '${DB_PASS}');
define('DB_NAME', '${DB_NAME}');
define('DB_PREFIX', '${DB_PREFIX}');
define('DB_PORT', '${DB_PORT}');
define('DB_CHARSET', '${DB_CHARSET}');
define('STEAMAPIKEY', '${STEAMAPIKEY}');
define('SB_EMAIL', '${SB_EMAIL}');
define('SB_NEW_SALT', '${SB_NEW_SALT}');
define('SB_SECRET_KEY', '${SB_SECRET_KEY}');
PHP
}

ensure_vendor() {
    if [[ -f "${WEB_ROOT}/includes/vendor/autoload.php" ]]; then
        return
    fi
    log "vendor/ missing — running composer install"
    cd "${WEB_ROOT}"
    composer install --no-progress --prefer-dist
}

ensure_cache() {
    # cache/ is read by SB_CACHE; templates_c/ is Smarty's default compile dir.
    mkdir -p "${WEB_ROOT}/cache" "${WEB_ROOT}/cache/sessions" "${WEB_ROOT}/templates_c"
    chown -R www-data:www-data "${WEB_ROOT}/cache" "${WEB_ROOT}/templates_c"
    chmod -R 0775 "${WEB_ROOT}/cache" "${WEB_ROOT}/templates_c"
}

main() {
    wait_for_db
    render_config
    ensure_vendor
    ensure_cache
    log "starting: $*"
    exec "$@"
}

main "$@"
