/**
 * Seed helpers for E2E specs.
 *
 * Specs that need DB rows (the marquee ban-list page, the command
 * palette, the player drawer, …) call these from inside `test.beforeEach`
 * so they run AFTER `truncateE2eDb()` has cleared the previous spec's
 * state.
 *
 * Why "via API" instead of an INSERT shim:
 *   - `bans.add` is the same surface the admin → add-ban form drives,
 *     so the seed exercises CSRF + permissions + the full Smarty/JSON
 *     dispatcher on every run. If #1123 quietly changes the wire
 *     format of `bans.add`, every spec that seeds a ban surfaces the
 *     break.
 *   - Avoids a second PHP shim alongside `reset-e2e-db.php`. The
 *     existing shim handles install + truncate; specs that need
 *     domain rows can drive them through the panel itself.
 *
 * The page MUST already be authenticated. The default storage state
 * minted in `fixtures/global-setup.ts` covers every spec except the
 * login spec, so callers don't have to do anything special — `goto('/')`
 * inside the helper just makes sure `window.sb` / `window.Actions` /
 * the CSRF meta tag are mounted before the `evaluate()` runs.
 */

import type { Page } from '@playwright/test';

interface SbApiEnvelopeShape {
    ok: boolean;
    data?: { bid?: number };
    error?: { code: string; message: string };
}

export interface SeededBan {
    bid: number;
    nickname: string;
    steam: string;
}

export interface SeedBanArgs {
    /** Player nickname stored on the ban row (`bans.name`). */
    nickname: string;
    /** Steam2 id (`STEAM_0:1:N` style). The handler normalises via SteamID::toSteam2. */
    steam: string;
    /** Free-text reason; defaults to `'e2e seed'`. */
    reason?: string;
    /** Length in MINUTES. `0` (default) is a permanent ban. */
    length?: number;
}

/**
 * Seed a permanent ban via the `bans.add` JSON action and return the
 * new bid. Throws on non-OK envelope so callers don't have to inspect.
 */
export async function seedBanViaApi(page: Page, seed: SeedBanArgs): Promise<SeededBan> {
    const reason = seed.reason ?? 'e2e seed';
    const length = seed.length ?? 0;

    // Same-origin navigation so the CSRF meta tag, the api.js client,
    // and the autogenerated Actions registry are all in scope. We
    // intentionally don't `waitForReady()` here because the home page
    // can carry skeletons (#1123 dashboard widgets) that aren't
    // relevant to the seed call.
    await page.goto('/');

    const envelope = await page.evaluate(
        async (args) => {
            // window.sb.api.call ships from web/scripts/api.js;
            // window.Actions from web/scripts/api-contract.js
            // (autogenerated). Cast through unknown so the spec's TS
            // build doesn't have to import the panel-side d.ts.
            const w = window as unknown as {
                sb: {
                    api: {
                        call: (
                            action: string,
                            params: Record<string, unknown>,
                        ) => Promise<{
                            ok: boolean;
                            data?: { bid?: number };
                            error?: { code: string; message: string };
                        }>;
                    };
                };
                Actions: Record<string, string>;
            };
            return await w.sb.api.call(w.Actions.BansAdd, {
                nickname: args.nickname,
                steam: args.steam,
                type: 0,
                ip: '',
                length: args.length,
                reason: args.reason,
            });
        },
        { nickname: seed.nickname, steam: seed.steam, reason, length },
    );

    const env = envelope as SbApiEnvelopeShape;
    if (!env.ok || env.data?.bid === undefined) {
        throw new Error(
            `seedBanViaApi: bans.add failed (ok=${env.ok}) — ${JSON.stringify(env)}`,
        );
    }
    return { bid: env.data.bid, nickname: seed.nickname, steam: seed.steam };
}
