CREATE TABLE sb_actions (
  id int(10) unsigned NOT NULL auto_increment,
  name varchar(64) NOT NULL,
  steam varchar(32) NOT NULL,
  ip varchar(15) NOT NULL,
  message text NOT NULL,
  server_id smallint(5) unsigned NOT NULL,
  admin_id smallint(5) unsigned NOT NULL,
  admin_ip varchar(32) NOT NULL,
  time timestamp NOT NULL default CURRENT_TIMESTAMP,
  PRIMARY KEY  (id),
  KEY server_id (server_id),
  KEY admin_id (admin_id)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8;

CREATE TABLE sb_admins (
  id smallint(5) unsigned NOT NULL auto_increment,
  name varchar(64) NOT NULL,
  auth enum('steam','name','ip') NOT NULL,
  identity varchar(64) NOT NULL,
  password varchar(64) NOT NULL,
  flags varchar(256) NOT NULL,
  group_id smallint(5) unsigned NOT NULL,
  email varchar(128) NOT NULL,
  language varchar(2) NOT NULL default 'en',
  theme varchar(32) NOT NULL default 'default',
  srv_password varchar(64) default NULL,
  validate varchar(64) default NULL,
  lastvisit timestamp NULL default NULL,
  PRIMARY KEY  (id),
  UNIQUE KEY name (name),
  UNIQUE KEY auth (auth,identity),
  KEY group_id (group_id)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE sb_admins_groups (
  admin_id int(10) unsigned NOT NULL,
  group_id int(10) unsigned NOT NULL,
  inherit_order int(10) NOT NULL,
  PRIMARY KEY  (admin_id,group_id)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE sb_bans (
  id mediumint(8) unsigned NOT NULL auto_increment,
  type tinyint(1) NOT NULL,
  steam varchar(32) NOT NULL,
  ip varchar(15) NOT NULL,
  name varchar(64) NOT NULL,
  created timestamp NOT NULL default CURRENT_TIMESTAMP,
  ends timestamp NOT NULL default '0000-00-00 00:00:00',
  reason varchar(255) NOT NULL,
  server_id smallint(5) unsigned NOT NULL,
  admin_id smallint(5) unsigned NOT NULL,
  admin_ip varchar(15) NOT NULL,
  unban_admin_id smallint(5) unsigned NOT NULL,
  unban_reason varchar(255) NOT NULL,
  unban_time timestamp NULL default NULL,
  PRIMARY KEY  (id),
  KEY server_id (server_id),
  KEY admin_id (admin_id),
  KEY unban_admin_id (unban_admin_id)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE sb_blocks (
  ban_id mediumint(8) unsigned NOT NULL,
  name varchar(64) NOT NULL,
  server_id smallint(5) unsigned NOT NULL,
  time timestamp NOT NULL default CURRENT_TIMESTAMP,
  KEY ban_id (ban_id),
  KEY server_id (server_id)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE sb_comments (
  id mediumint(8) unsigned NOT NULL auto_increment,
  type varchar(1) NOT NULL,
  ban_id mediumint(8) unsigned NOT NULL,
  admin_id smallint(5) unsigned NOT NULL,
  message varchar(255) NOT NULL,
  time timestamp NOT NULL default CURRENT_TIMESTAMP,
  edit_admin_id smallint(5) unsigned NOT NULL,
  edit_time timestamp NULL default NULL,
  PRIMARY KEY  (id),
  KEY ban_id (ban_id),
  KEY admin_id (admin_id),
  KEY edit_admin_id (edit_admin_id)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE sb_demos (
  ban_id mediumint(8) unsigned NOT NULL,
  type varchar(1) NOT NULL,
  filename varchar(255) NOT NULL,
  KEY ban_id (ban_id)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE sb_groups (
  id smallint(5) unsigned NOT NULL auto_increment,
  type varchar(1) NOT NULL,
  name varchar(32) NOT NULL,
  flags varchar(256) NOT NULL,
  PRIMARY KEY  (id)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE sb_group_immunity (
  group_id int(10) unsigned NOT NULL,
  other_id int(10) unsigned NOT NULL,
  PRIMARY KEY  (group_id,other_id)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE sb_group_overrides (
  group_id int(10) unsigned NOT NULL,
  type enum('command','group') NOT NULL,
  name varchar(32) NOT NULL,
  access enum('allow','deny') NOT NULL,
  PRIMARY KEY  (group_id,type,name)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE sb_log (
  id int(10) unsigned NOT NULL auto_increment,
  type enum('m','w','e') NOT NULL,
  title varchar(64) NOT NULL,
  message varchar(255) NOT NULL,
  function varchar(255) NOT NULL,
  query varchar(255) NOT NULL,
  admin_id smallint(5) unsigned NOT NULL,
  admin_ip varchar(15) NOT NULL,
  time timestamp NOT NULL default CURRENT_TIMESTAMP,
  PRIMARY KEY  (id),
  KEY admin_id (admin_id)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE sb_mods (
  id tinyint(3) unsigned NOT NULL auto_increment,
  name varchar(32) NOT NULL,
  folder varchar(32) NOT NULL,
  icon varchar(32) NOT NULL,
  enabled tinyint(1) NOT NULL default '1',
  PRIMARY KEY  (id)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

INSERT INTO sb_mods (name, folder, icon, enabled) VALUES
('Half-Life 2 Deathmatch', 'hl2mp', 'hl2dm.png', 1),
('Counter-Strike: Source', 'cstrike', 'csource.png', 1),
('Day of Defeat: Source', 'dod', 'dods.png', 1),
('Insurgency: Source', 'insurgency', 'ins.gif', 1),
('Dystopia', 'dystopia_v1', 'dys.gif', 1),
('Hidden: Source', 'hidden', 'hidden.png', 1),
('Half-Life 2 Capture the Flag', 'hl2ctf', 'hl2ctf.png', 1),
('Pirates Vikings and Knights II', 'pvkii', 'pvkii.gif', 1),
('Perfect Dark: Source', 'pdark', 'pdark.gif', 1),
('The Ship', 'ship', 'ship.gif', 1),
('Fortress Forever', 'FortressForever', 'hl2-fortressforever.gif', 1),
('Team Fortress 2', 'tf', 'tf2.gif', 1),
('Zombie Panic', 'zps', 'zps.gif', 1),
('Garry''s Mod', 'garrysmod', 'gmod.png', 1),
('Left 4 Dead', 'left4dead', 'l4d.png', 1);

CREATE TABLE sb_plugins (
  name varchar(32) NOT NULL,
  enabled tinyint(1) NOT NULL default '1',
  UNIQUE KEY name (name)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE sb_protests (
  id mediumint(8) unsigned NOT NULL auto_increment,
  ban_id mediumint(8) unsigned NOT NULL,
  reason varchar(255) NOT NULL,
  email varchar(128) NOT NULL,
  ip varchar(15) NOT NULL,
  archived tinyint(1) NOT NULL default '0',
  time timestamp NOT NULL default CURRENT_TIMESTAMP,
  PRIMARY KEY  (id),
  KEY ban_id (ban_id)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE sb_quotes (
  name varchar(25) NOT NULL,
  text varchar(255) NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

INSERT INTO sb_quotes (name, text) VALUES
('Viper', 'Buy a new PC!'),
('Brizad', 'I''m not lazy! I just utilize technical resources!'),
('sslice', 'I need to mow the lawn'),
('Viper', 'Like A Glove!'),
('Viper', 'You''re a Noob and You Know It!'),
('Viper', 'Get your ass ingame'),
('Viper', 'Mother F***ing Pieces of Sh**'),
('[Everyone]', 'Shut up Bam'),
('Viper', 'Hi OllyBunch'),
('[Unknown]', 'Procrastination is like masturbation. Sure it feels good, but in the end you''re only f***ing yourself!'),
('SteamFriend', 'Rave''s momma so fat, she sat on the beach and Greenpeace threw her in'),
('Faith', 'I''m just getting a beer'),
('Viper', 'To be honest{if $logged_in} {$username}{/if}..., I DON''T CARE!'),
('teame06', 'Yams'),
('gdogg', 'built in cheat 1.6 - my friend told me theres a cheat where u can buy a car door and run around and it makes u invincible....'),
('BAILOPAN', 'i just join conversation when i see a chance to tell people they might be wrong, then i quickly leave, LIKE A BAT'),
('[Everyone]', 'Let''s just blame it on FlyingMongoose'),
('SirTiger', 'I wish my lawn was emo, so it would cut itself'),
('Olly', 'Oh no! I''ve overflowed my balls!'),
('DamagedSoul', 'Good night, talking desk lamp.'),
('Alfred', 'Looks like that custom server.dll you injected in the way is corrupting the vtables of our interfaces.');

CREATE TABLE sb_servers (
  id smallint(5) unsigned NOT NULL auto_increment,
  ip varchar(15) NOT NULL,
  port smallint(5) unsigned NOT NULL,
  rcon varchar(32) NOT NULL,
  mod_id tinyint(3) unsigned NOT NULL,
  PRIMARY KEY  (id),
  KEY mod_id (mod_id)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE sb_servers_groups (
  server_id int(10) NOT NULL,
  group_id int(10) NOT NULL,
  PRIMARY KEY  (server_id,group_id)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE sb_settings (
  name varchar(32) NOT NULL,
  value text NOT NULL,
  UNIQUE KEY name (name)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

INSERT INTO sb_settings (name, value) VALUES
('banlist.bansperpage', '25'),
('banlist.hideadminname', '0'),
('bans.customreasons', ''),
('config.dateformat', 'm-d-y H:i'),
('config.debug', '0'),
('config.defaultpage', '0'),
('config.enableprotest', '1'),
('config.enablesubmit', '1'),
('config.exportpublic', '0'),
('config.language', 'en'),
('config.password.minlength', '4'),
('config.summertime', '0'),
('config.theme', 'default'),
('config.timezone', '1'),
('config.version', '191'),
('dash.intro.text', ''),
('dash.intro.title', ''),
('dash.lognopopup', '0'),
('banlist.nocountryfetch', '0');

CREATE TABLE sb_srvgroups (
  id smallint(5) unsigned NOT NULL auto_increment,
  name varchar(32) NOT NULL,
  flags bigint(20) unsigned NOT NULL,
  immunity smallint(5) unsigned NOT NULL default '0',
  PRIMARY KEY  (id)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE sb_submissions (
  id mediumint(8) unsigned NOT NULL auto_increment,
  name varchar(64) NOT NULL,
  steam varchar(32) NOT NULL,
  ip varchar(15) NOT NULL,
  reason varchar(255) NOT NULL,
  server_id smallint(5) unsigned NOT NULL,
  subname varchar(64) NOT NULL,
  subemail varchar(128) NOT NULL,
  subip varchar(15) NOT NULL,
  archived tinyint(1) NOT NULL default '0',
  time timestamp NOT NULL default CURRENT_TIMESTAMP,
  PRIMARY KEY  (id),
  KEY server_id (server_id)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE sb_translations (
  name varchar(128) NOT NULL,
  language varchar(2) NOT NULL,
  value text NOT NULL,
  PRIMARY KEY  (name,language)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

INSERT INTO sb_translations (name, language, value) VALUES
('access_denied', 'de', 'Zugriff verweigert'),
('access_denied', 'en', 'Access Denied'),
('access_denied', 'nl', 'Toegang Geweigerd'),
('action', 'de', 'Aktion'),
('action', 'en', 'Action'),
('action', 'nl', 'Actie'),
('actions_log', 'de', 'Aktions Log'),
('actions_log', 'en', 'Actions Log'),
('actions_log', 'nl', 'Acties Log'),
('add_admin', 'de', 'Admin hinzufügen'),
('add_admin', 'en', 'Add admin'),
('add_admin', 'nl', 'Admin toevoegen'),
('add_admins', 'de', 'Admins hinzufügen'),
('add_admins', 'en', 'Add admins'),
('add_admins', 'nl', 'Admins toevoegen'),
('add_ban', 'de', 'Ban hinzufügen'),
('add_ban', 'en', 'Add ban'),
('add_ban', 'nl', 'Ban toevoegen'),
('add_bans', 'de', 'Bans hinzufügen'),
('add_bans', 'en', 'Add bans'),
('add_bans', 'nl', 'Bans toevoegen'),
('add_comment', 'de', 'Kommentar hinzufügen'),
('add_comment', 'en', 'Add comment'),
('add_comment', 'nl', 'Reactie toevoegen'),
('add_group', 'de', 'Gruppe hinzufügen'),
('add_group', 'en', 'Add group'),
('add_group', 'nl', 'Groep toevoegen'),
('add_groups', 'de', 'Gruppen hinzufügen'),
('add_groups', 'en', 'Add groups'),
('add_groups', 'nl', 'Groepen toevoegen'),
('add_mod', 'de', 'Mod hinzufügen'),
('add_mod', 'en', 'Add mod'),
('add_mod', 'nl', 'Mod toevoegen'),
('add_mods', 'de', 'Mods hinzufügen'),
('add_mods', 'en', 'Add mods'),
('add_mods', 'nl', 'Mods toevoegen'),
('add_server', 'de', 'Server hinzufügen'),
('add_server', 'en', 'Add server'),
('add_server', 'nl', 'Server toevoegen'),
('add_servers', 'de', 'Server hinzufügen'),
('add_servers', 'en', 'Add servers'),
('add_servers', 'nl', 'Servers toevoegen'),
('admin', 'de', 'Admin'),
('admin', 'en', 'Admin'),
('admin', 'nl', 'Admin'),
('administration', 'de', 'Administration'),
('administration', 'en', 'Administration'),
('administration', 'nl', 'Administratie'),
('administration_desc', 'de', 'Das ist die Verwaltungsoberfläche von SourceBans, wo Sie neue Admins erstellen können, neue Server hinzufügen, usw.'),
('administration_desc', 'en', 'This is the control panel for SourceBans where you can setup new admins, add new servers, etc.'),
('administration_desc', 'nl', 'This is the control panel for SourceBans where you can setup new admins, add new servers, etc.'),
('admins', 'de', 'Admins'),
('admins', 'en', 'Admins'),
('admins', 'nl', 'Admins'),
('admins_in_group', 'de', 'Admins in Gruppe'),
('admins_in_group', 'en', 'Admins in group'),
('admins_in_group', 'nl', 'Admins in groep'),
('admin_information', 'de', 'Admin Informationen'),
('admin_information', 'en', 'Admin Information'),
('admin_information', 'nl', 'Admin Informatie'),
('advanced_search', 'de', 'Erweiterte Suche'),
('advanced_search', 'en', 'Advanced Search'),
('advanced_search', 'nl', 'Geavanceerd Zoeken'),
('archive', 'de', 'Archiv'),
('archive', 'en', 'Archive'),
('archive', 'nl', 'Archief'),
('archived_protests', 'de', 'Archivierte Proteste'),
('archived_protests', 'en', 'Archived protests'),
('archived_protests', 'nl', 'Gearchiveerde protesten'),
('archived_submissions', 'de', 'Archivierte Einsendungen'),
('archived_submissions', 'en', 'Archived submissions'),
('archived_submissions', 'nl', 'Gearchiveerde submissies'),
('back', 'de', 'Zurück'),
('back', 'en', 'Back'),
('back', 'nl', 'Terug'),
('bans', 'de', 'Bans'),
('bans', 'en', 'Bans'),
('bans', 'nl', 'Bans'),
('ban_information', 'de', 'Ban Informationen'),
('ban_information', 'en', 'Ban Information'),
('ban_information', 'nl', 'Ban Informatie'),
('ban_list', 'de', 'Ban Liste'),
('ban_list', 'en', 'Ban list'),
('ban_list', 'nl', 'Ban lijst'),
('ban_list_desc', 'de', 'Alle Bans in der Datenbank können hier eingesehen werden.'),
('ban_list_desc', 'en', 'All of the bans in the database can be viewed from here.'),
('ban_list_desc', 'nl', 'All of the bans in the database can be viewed from here.'),
('ban_protests', 'de', 'Ban Proteste'),
('ban_protests', 'en', 'Ban protests'),
('ban_protests', 'nl', 'Ban protesten'),
('ban_submissions', 'de', 'Ban Einsendungen'),
('ban_submissions', 'en', 'Ban submissions'),
('ban_submissions', 'nl', 'Ban submissies'),
('by', 'de', 'von'),
('by', 'en', 'By'),
('by', 'nl', 'Door'),
('click', 'de', 'Klick'),
('click', 'en', 'Click'),
('click', 'nl', 'Klik'),
('comment', 'de', 'Kommentieren'),
('comment', 'en', 'Comment'),
('comment', 'nl', 'Reactie'),
('comments', 'de', 'Kommentare'),
('comments', 'en', 'Comments'),
('comments', 'nl', 'Reacties'),
('confirm', 'de', 'Bestätigen'),
('confirm', 'en', 'Confirm'),
('confirm', 'nl', 'Bevestig'),
('confirm_password', 'de', 'Passwort bestätigen'),
('confirm_password', 'en', 'Confirm password'),
('confirm_password', 'nl', 'Bevestig wachtwoord'),
('connect', 'de', 'Verbinden'),
('connect', 'en', 'Connect'),
('connect', 'nl', 'Verbinden'),
('connection_blocks', 'de', 'Verbindungen geblockt'),
('connection_blocks', 'en', 'Connection blocks'),
('connection_blocks', 'nl', 'Verbindingen geblokkeerd'),
('country', 'de', 'Land'),
('country', 'en', 'Country'),
('country', 'nl', 'Land'),
('current_password', 'de', 'Derzeitiges Passwort'),
('current_password', 'en', 'Current password'),
('current_password', 'nl', 'Huidige wachtwoord'),
('dashboard', 'de', 'Dashboard'),
('dashboard', 'en', 'Dashboard'),
('dashboard', 'nl', 'Dashboard'),
('dashboard_desc', 'de', 'Diese Seite zeigt eine Übersicht der Bans und Server.'),
('dashboard_desc', 'en', 'This page shows an overview of your bans and servers.'),
('dashboard_desc', 'nl', 'This page shows an overview of your bans and servers.'),
('date', 'de', 'Datum'),
('date', 'en', 'Date'),
('date', 'nl', 'Datum'),
('day', 'de', 'Tag'),
('day', 'en', 'day'),
('day', 'nl', 'dag'),
('days', 'de', 'Tage'),
('days', 'en', 'days'),
('days', 'nl', 'dagen'),
('delete', 'de', 'Löschen'),
('delete', 'en', 'Delete'),
('delete', 'nl', 'Verwijderen'),
('delete_admin', 'de', 'Admin löschen'),
('delete_admin', 'en', 'Delete admin'),
('delete_admin', 'nl', 'Admin verwijderen'),
('delete_admins', 'de', 'Admins löschen'),
('delete_admins', 'en', 'Delete admins'),
('delete_admins', 'nl', 'Admins verwijderen'),
('delete_ban', 'de', 'Ban löschen'),
('delete_ban', 'en', 'Delete ban'),
('delete_ban', 'nl', 'Ban verwijderen'),
('delete_bans', 'de', 'Bans löschen'),
('delete_bans', 'en', 'Delete bans'),
('delete_bans', 'nl', 'Bans verwijderen'),
('delete_groups', 'de', 'Gruppen löschen'),
('delete_groups', 'en', 'Delete groups'),
('delete_groups', 'nl', 'Groepen verwijderen'),
('delete_mods', 'de', 'Mods löschen'),
('delete_mods', 'en', 'Delete mods'),
('delete_mods', 'nl', 'Mods verwijderen'),
('delete_servers', 'de', 'Server löschen'),
('delete_servers', 'en', 'Delete servers'),
('delete_servers', 'nl', 'Servers verwijderen'),
('demo', 'de', 'Demo'),
('demo', 'en', 'Demo'),
('demo', 'nl', 'Demo'),
('displaying_results', 'de', 'Zeige {$start} - {$end} von {$total} Ergebnissen'),
('displaying_results', 'en', 'Displaying {$start} - {$end} of {$total} results'),
('displaying_results', 'nl', 'Resultaten {$start} - {$end} van {$total} weergegeven'),
('edit', 'de', 'Ändern'),
('edit', 'en', 'Edit'),
('edit', 'nl', 'Bewerken'),
('edit_admins', 'de', 'Admins bearbeiten'),
('edit_admins', 'en', 'Edit admins'),
('edit_admins', 'nl', 'Admins bewerken'),
('edit_all_bans', 'de', 'Alle Bans bearbeiten'),
('edit_all_bans', 'en', 'Edit all bans'),
('edit_all_bans', 'nl', 'Alle bans bewerken'),
('edit_ban', 'de', 'Ban bearbeiten'),
('edit_ban', 'en', 'Edit ban'),
('edit_ban', 'nl', 'Ban bewerken'),
('edit_details', 'de', 'Details bearbeiten'),
('edit_details', 'en', 'Edit details'),
('edit_details', 'nl', 'Details bewerken'),
('edit_groups', 'de', 'Gruppen bearbeiten'),
('edit_groups', 'en', 'Edit groups'),
('edit_groups', 'nl', 'Groepen bewerken'),
('edit_group_bans', 'de', 'Gruppenbans bearbeiten'),
('edit_group_bans', 'en', 'Edit group bans'),
('edit_group_bans', 'nl', 'Groep bans bewerken'),
('edit_mod', 'de', 'Mod bearbeiten'),
('edit_mod', 'en', 'Edit mod'),
('edit_mod', 'nl', 'Mod bewerken'),
('edit_mods', 'de', 'Mods bearbeiten'),
('edit_mods', 'en', 'Edit mods'),
('edit_mods', 'nl', 'Mods bewerken'),
('edit_own_bans', 'de', 'Eigene Bans bearbeiten'),
('edit_own_bans', 'en', 'Edit own bans'),
('edit_own_bans', 'nl', 'Eigen bans bewerken'),
('edit_permissions', 'de', 'Rechte bearbeiten'),
('edit_permissions', 'en', 'Edit permissions'),
('edit_permissions', 'nl', 'Permissies bewerken'),
('edit_server', 'de', 'Server bearbeiten'),
('edit_server', 'en', 'Edit server'),
('edit_server', 'nl', 'Server bewerken'),
('edit_servers', 'de', 'Server bearbeiten'),
('edit_servers', 'en', 'Edit servers'),
('edit_servers', 'nl', 'Servers bewerken'),
('email_address', 'de', 'E-mail Adresse'),
('email_address', 'en', 'E-mail address'),
('email_address', 'nl', 'E-mailadres'),
('email_notifications', 'de', 'E-mail Benachrichtigungen'),
('email_notifications', 'en', 'E-mail Notifications'),
('email_notifications', 'nl', 'E-mail Kennisgevingen'),
('error', 'de', 'Fehler'),
('error', 'en', 'Error'),
('error', 'nl', 'Foutmelding'),
('expired', 'de', 'Abgelaufen'),
('expired', 'en', 'Expired'),
('expired', 'nl', 'Verlopen'),
('expires_on', 'de', 'Läuft ab am'),
('expires_on', 'en', 'Expires on'),
('expires_on', 'nl', 'Vervalt op'),
('file', 'de', 'Datei'),
('file', 'en', 'File'),
('file', 'nl', 'Bestand'),
('folder', 'de', 'Ordner'),
('folder', 'en', 'Folder'),
('folder', 'nl', 'Map'),
('group', 'de', 'Gruppe'),
('group', 'en', 'Group'),
('group', 'nl', 'Groep'),
('groups', 'de', 'Gruppen'),
('groups', 'en', 'Groups'),
('groups', 'nl', 'Groepen'),
('hide_inactive', 'de', 'Inaktive verstecken'),
('hide_inactive', 'en', 'Hide inactive'),
('hide_inactive', 'nl', 'Inactieve verbergen'),
('hostname', 'de', 'Hostname'),
('hostname', 'en', 'Hostname'),
('hostname', 'nl', 'Hostnaam'),
('hour', 'de', 'Stunde'),
('hour', 'en', 'hour'),
('hour', 'nl', 'uur'),
('hours', 'de', 'Stunden'),
('hours', 'en', 'hours'),
('hours', 'nl', 'uren'),
('icon', 'de', 'Icon'),
('icon', 'en', 'Icon'),
('icon', 'nl', 'Pictogram'),
('import_admins', 'de', 'Admins importieren'),
('import_admins', 'en', 'Import admins'),
('import_admins', 'nl', 'Admins importeren'),
('import_bans', 'de', 'Bans importieren'),
('import_bans', 'en', 'Import bans'),
('import_bans', 'nl', 'Bans importeren'),
('import_groups', 'de', 'Gruppen importieren'),
('import_groups', 'en', 'Import groups'),
('import_groups', 'nl', 'Groepen importeren'),
('import_servers', 'de', 'Server importieren'),
('import_servers', 'en', 'Import servers'),
('import_servers', 'nl', 'Servers importeren'),
('information', 'de', 'Information'),
('information', 'en', 'Information'),
('information', 'nl', 'Informatie'),
('invoked_on', 'de', 'Ausgesprochen am'),
('invoked_on', 'en', 'Invoked on'),
('invoked_on', 'nl', 'Ingeroepen op'),
('ip_address', 'de', 'IP Adresse'),
('ip_address', 'en', 'IP Address'),
('ip_address', 'nl', 'IP Adres'),
('language', 'de', 'Sprache'),
('language', 'en', 'Language'),
('language', 'nl', 'Taal'),
('latest_bans', 'de', 'Zuletzt hinzugefügte Bans'),
('latest_bans', 'en', 'Latest Added Bans'),
('latest_bans', 'nl', 'Laatst Toegevoegde Bans'),
('latest_blocked', 'de', 'Zuletzt geblockte Spieler'),
('latest_blocked', 'en', 'Latest Players Blocked'),
('latest_blocked', 'nl', 'Laatst Geblokkeerde Spelers'),
('latest_release', 'de', 'Letztes Release'),
('latest_release', 'en', 'Latest release'),
('latest_release', 'nl', 'Laatste release'),
('length', 'de', 'Länge'),
('length', 'en', 'Length'),
('length', 'nl', 'Lengte'),
('list_admins', 'de', 'Admins auflisten'),
('list_admins', 'en', 'List admins'),
('list_admins', 'nl', 'Admins weergeven'),
('list_groups', 'de', 'Gruppen auflisten'),
('list_groups', 'en', 'List groups'),
('list_groups', 'nl', 'Groepen weergeven'),
('list_mods', 'de', 'Mods auflisten'),
('list_mods', 'en', 'List mods'),
('list_mods', 'nl', 'Mods weergeven'),
('list_servers', 'de', 'Server auflisten'),
('list_servers', 'en', 'List servers'),
('list_servers', 'nl', 'Servers weergeven'),
('login', 'de', 'Einloggen'),
('login', 'en', 'Login'),
('login', 'nl', 'Inloggen'),
('logout', 'de', 'Ausloggen'),
('logout', 'en', 'Logout'),
('logout', 'nl', 'Uitloggen'),
('map', 'de', 'Karte'),
('map', 'en', 'Map'),
('map', 'nl', 'Map'),
('minute', 'de', 'Minute'),
('minute', 'en', 'minute'),
('minute', 'nl', 'minuut'),
('minutes', 'de', 'Minuten'),
('minutes', 'en', 'minutes'),
('minutes', 'nl', 'minuten'),
('mods', 'de', 'Mods'),
('mods', 'en', 'Mods'),
('mods', 'nl', 'Mods'),
('month', 'de', 'Monat'),
('month', 'en', 'month'),
('month', 'nl', 'maand'),
('months', 'de', 'Monate'),
('months', 'en', 'months'),
('months', 'nl', 'maanden'),
('name', 'de', 'Name'),
('name', 'en', 'Name'),
('name', 'nl', 'Naam'),
('new', 'de', 'Neu'),
('new', 'en', 'New'),
('new', 'nl', 'Nieuw'),
('new_password', 'de', 'Neues Passwort'),
('new_password', 'en', 'New password'),
('new_password', 'nl', 'Nieuwe wachtwoord'),
('next', 'de', 'nächste'),
('next', 'en', 'next'),
('next', 'nl', 'volgende'),
('no', 'de', 'Nein'),
('no', 'en', 'No'),
('no', 'nl', 'Nee'),
('none', 'de', 'Keine'),
('none', 'en', 'None'),
('none', 'nl', 'Geen'),
('notify_protests', 'de', 'Protest E-Mail benachrichtigen'),
('notify_protests', 'en', 'Protest email notifying'),
('notify_protests', 'nl', 'Protest e-mail kennisgeving'),
('notify_submissions', 'de', 'Einsendung E-Mail benachrichtigen'),
('notify_submissions', 'en', 'Submission email notifying'),
('notify_submissions', 'nl', 'Submissie e-mail kennisgeving'),
('not_applicable', 'de', 'Nicht anwendbar'),
('not_applicable', 'en', 'Not applicable'),
('not_applicable', 'nl', 'Niet van toepassing'),
('no_players', 'de', 'Keine Spieler auf dem Server'),
('no_players', 'en', 'No players in the server'),
('no_players', 'nl', 'Geen spelers in de server'),
('password', 'de', 'Passwort'),
('password', 'en', 'Password'),
('password', 'nl', 'Wachtwoord'),
('permanent', 'de', 'Permanent'),
('permanent', 'en', 'Permanent'),
('permanent', 'nl', 'Permanent'),
('players', 'de', 'Spieler'),
('players', 'en', 'Players'),
('players', 'nl', 'Spelers'),
('please_wait', 'de', 'Bitte warten'),
('please_wait', 'en', 'Please wait'),
('please_wait', 'nl', 'Even geduld'),
('port', 'de', 'Port'),
('port', 'en', 'Port'),
('port', 'nl', 'Poort'),
('powered_by', 'de', 'Powered by'),
('powered_by', 'en', 'Powered by'),
('powered_by', 'nl', 'Aangedreven door'),
('prev', 'de', 'vorherige'),
('prev', 'en', 'prev'),
('prev', 'nl', 'vorige'),
('protest_ban', 'de', 'Ban protestieren'),
('protest_ban', 'en', 'Protest ban'),
('protest_ban', 'nl', 'Ban protesteren'),
('protest_ban_desc', 'de', 'Hier können Sie gegen Ihren Ban protestieren und belegen, warum Sie entbannt werden sollten.'),
('protest_ban_desc', 'en', 'Here you can protest your ban. And prove your case as to why you should be unbanned.'),
('protest_ban_desc', 'nl', 'Here you can protest your ban. And prove your case as to why you should be unbanned.'),
('protest_information', 'de', 'Protest Informationen'),
('protest_information', 'en', 'Protest Information'),
('protest_information', 'nl', 'Protest Informatie'),
('reason', 'de', 'Grund'),
('reason', 'en', 'Reason'),
('reason', 'nl', 'Reden'),
('reban', 'de', 'Nochmal bannen'),
('reban', 'en', 'Reban'),
('reban', 'nl', 'Herbannen'),
('refresh', 'de', 'Erneuern'),
('refresh', 'en', 'Refresh'),
('refresh', 'nl', 'Vernieuwen'),
('remember_me', 'de', 'Eingeloggt bleiben?'),
('remember_me', 'en', 'Remember me'),
('remember_me', 'nl', 'Onthoud mij'),
('score', 'de', 'Punkte'),
('score', 'en', 'Score'),
('score', 'nl', 'Punten'),
('search', 'de', 'Suchen'),
('search', 'en', 'Search'),
('search', 'nl', 'Zoeken'),
('search_bans', 'de', 'Bans durchsuchen'),
('search_bans', 'en', 'Search Bans'),
('search_bans', 'nl', 'Bans Doorzoeken'),
('server', 'de', 'Server'),
('server', 'en', 'Server'),
('server', 'nl', 'Server'),
('servers', 'de', 'Servers'),
('servers', 'en', 'Servers'),
('servers', 'nl', 'Servers'),
('servers_desc', 'de', 'Alle Server und ihre Status können hier eingesehen werden.'),
('servers_desc', 'en', 'All of your servers and their status can be viewed here.'),
('servers_desc', 'nl', 'All of your servers and their status can be viewed here.'),
('servers_in_group', 'de', 'Server in Gruppe'),
('servers_in_group', 'en', 'Servers in group'),
('servers_in_group', 'nl', 'Servers in groep'),
('servers_list', 'de', 'Server Liste'),
('servers_list', 'en', 'Servers List'),
('servers_list', 'nl', 'Servers Lijst'),
('server_admin_group', 'de', 'Server Admin Gruppe'),
('server_admin_group', 'en', 'Server Admin Group'),
('server_admin_group', 'nl', 'Server Admin Groep'),
('server_admin_groups', 'de', 'Server Admin Gruppen'),
('server_admin_groups', 'en', 'Server Admin Groups'),
('server_admin_groups', 'nl', 'Server Admin Groepen'),
('server_group', 'de', 'Server Gruppen'),
('server_group', 'en', 'Server Group'),
('server_group', 'nl', 'Server Groep'),
('server_groups', 'de', 'Server Gruppen'),
('server_groups', 'en', 'Server Groups'),
('server_groups', 'nl', 'Server Groepen'),
('server_information', 'de', 'Server Informationen'),
('server_information', 'en', 'Server Information'),
('server_information', 'nl', 'Server Informatie'),
('server_permissions', 'de', 'Server Rechte'),
('server_permissions', 'en', 'Server Permissions'),
('server_permissions', 'nl', 'Server Permissies'),
('settings', 'de', 'Einstellungen'),
('settings', 'en', 'Settings'),
('settings', 'nl', 'Instellingen'),
('submission_information', 'de', 'Einsendungsinformationen'),
('submission_information', 'en', 'Submission Information'),
('submission_information', 'nl', 'Submissie Informatie'),
('submit', 'de', 'Senden'),
('submit', 'en', 'Submit'),
('submit', 'nl', 'Indienen'),
('submit_ban', 'de', 'Ban einsenden'),
('submit_ban', 'en', 'Submit ban'),
('submit_ban', 'nl', 'Ban indienen'),
('submit_ban_desc', 'de', 'Hier können Sie eine Demo oder einen Screenshot eines vermeintlichen Cheaters einsenden. Einer der Admins wird sich dann darum kümmern.'),
('submit_ban_desc', 'en', 'You can submit a demo or screenshot of a suspected cheater here. It will then be up for review by one of the admins.'),
('submit_ban_desc', 'nl', 'You can submit a demo or screenshot of a suspected cheater here. It will then be up for review by one of the admins.'),
('system_log', 'de', 'System Log'),
('system_log', 'en', 'System Log'),
('system_log', 'nl', 'Systeem Log'),
('themes', 'de', 'Themas'),
('themes', 'en', 'Themes'),
('themes', 'nl', 'Thema''s'),
('time', 'de', 'Zeit'),
('time', 'en', 'Time'),
('time', 'nl', 'Tijd'),
('total', 'de', 'Insgesamt'),
('total', 'en', 'Total'),
('total', 'nl', 'Aantal'),
('total_admins', 'de', 'Admins insgesamt'),
('total_admins', 'en', 'Total admins'),
('total_admins', 'nl', 'Aantal admins'),
('total_bans', 'de', 'Bans insgesamt'),
('total_bans', 'en', 'Total bans'),
('total_bans', 'nl', 'Aantal bans'),
('total_blocked', 'de', 'Insgesamt Gestoppt'),
('total_blocked', 'en', 'Total stopped'),
('total_blocked', 'nl', 'Aantal gestopt'),
('total_demo_size', 'de', 'Demogröße insgesamt'),
('total_demo_size', 'en', 'Total demo size'),
('total_demo_size', 'nl', 'Totale demo grootte'),
('total_protests', 'de', 'Proteste insgesamt'),
('total_protests', 'en', 'Total protests'),
('total_protests', 'nl', 'Aantal protesten'),
('total_servers', 'de', 'Server insgesammt'),
('total_servers', 'en', 'Total servers'),
('total_servers', 'nl', 'Aantal servers'),
('total_submissions', 'de', 'Einsendungen insgesamt'),
('total_submissions', 'en', 'Total submissions'),
('total_submissions', 'nl', 'Aantal submissies'),
('to_archive', 'de', 'Archivieren'),
('to_archive', 'en', 'Archive'),
('to_archive', 'nl', 'Archiveren'),
('to_ban', 'de', 'Bannen'),
('to_ban', 'en', 'Ban'),
('to_ban', 'nl', 'Bannen'),
('unban', 'de', 'Entbannen'),
('unban', 'en', 'Unban'),
('unban', 'nl', 'Unbannen'),
('unban_all_bans', 'de', 'Alle Bans entbannen'),
('unban_all_bans', 'en', 'Unban all bans'),
('unban_all_bans', 'nl', 'Alle bans unbannen'),
('unban_group_bans', 'de', 'Gruppen Bans entbannen'),
('unban_group_bans', 'en', 'Unban group bans'),
('unban_group_bans', 'nl', 'Groep bans unbannen'),
('unban_own_bans', 'de', 'Eigene Bans entbannen'),
('unban_own_bans', 'en', 'Unban own bans'),
('unban_own_bans', 'nl', 'Eigen bans unbannen'),
('unknown', 'de', 'Unbekannt'),
('unknown', 'en', 'Unknown'),
('unknown', 'nl', 'Onbekend'),
('username', 'de', 'Benutzername'),
('username', 'en', 'Username'),
('username', 'nl', 'Gebruikersnaam'),
('version', 'de', 'Version'),
('version', 'en', 'Version'),
('version', 'nl', 'Versie'),
('version_information', 'de', 'Version Informationen'),
('version_information', 'en', 'Version Information'),
('version_information', 'nl', 'Versie Informatie'),
('view_permissions', 'de', 'Rechte ansehen'),
('view_permissions', 'en', 'View permissions'),
('view_permissions', 'nl', 'Permissies bekijken'),
('warning', 'de', 'Warnung'),
('warning', 'en', 'Warning'),
('warning', 'nl', 'Waarschuwing'),
('web_admin_group', 'de', 'Web Admin Gruppe'),
('web_admin_group', 'en', 'Web Admin Group'),
('web_admin_group', 'nl', 'Web Admin Groep'),
('web_admin_groups', 'de', 'Web Admin Gruppen'),
('web_admin_groups', 'en', 'Web Admin Groups'),
('web_admin_groups', 'nl', 'Web Admin Groepen'),
('web_permissions', 'de', 'Web Rechte'),
('web_permissions', 'en', 'Web Permissions'),
('web_permissions', 'nl', 'Web Permissies'),
('week', 'de', 'Woche'),
('week', 'en', 'week'),
('week', 'nl', 'week'),
('weeks', 'de', 'Wochen'),
('weeks', 'en', 'weeks'),
('weeks', 'nl', 'weken'),
('welcome', 'de', 'Willkommen'),
('welcome', 'en', 'Welcome'),
('welcome', 'nl', 'Welkom'),
('yes', 'de', 'Ja'),
('yes', 'en', 'Yes'),
('yes', 'nl', 'Ja'),
('your_account', 'de', 'Dein Account'),
('your_account', 'en', 'Your account'),
('your_account', 'nl', 'Jouw account'),
('your_permissions', 'en', 'Your permissions'),
('your_permissions', 'nl', 'Jouw permissies'),
('enabled', 'de', 'Eingeschaltet'),
('enabled', 'en', 'Enabled'),
('enabled', 'nl', 'Ingeschakeld'),
('disabled', 'de', 'Ausgeschaltet'),
('disabled', 'en', 'Disabled'),
('disabled', 'nl', 'Uitgeschakeld'),
('edit_group', 'de', 'Gruppe ändern'),
('edit_group', 'en', 'Edit group'),
('edit_group', 'nl', 'Groep bewerken'),
('ban_details', 'de', 'Ban Details'),
('ban_details', 'en', 'Ban Details');
